// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFqkw05jiFSe3DBHwL3bFJDXdHew3IWtw',
    appId: '1:1084788300297:web:215fdeb981dab84c7b36d8',
    messagingSenderId: '1084788300297',
    projectId: 'school-proect-8f2bb',
    authDomain: 'school-proect-8f2bb.firebaseapp.com',
    storageBucket: 'school-proect-8f2bb.firebasestorage.app',
    measurementId: 'G-Z1NPLMZ37D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-_t6BaXFD0nQPKV4kL7Cuzt6NWQimewM',
    appId: '1:1084788300297:android:10ad2575d7eb26197b36d8',
    messagingSenderId: '1084788300297',
    projectId: 'school-proect-8f2bb',
    storageBucket: 'school-proect-8f2bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXvnvTR06b3HW89YmzLXVn_-7EsFXK5Vk',
    appId: '1:1084788300297:ios:c33fe4ca2299ea437b36d8',
    messagingSenderId: '1084788300297',
    projectId: 'school-proect-8f2bb',
    storageBucket: 'school-proect-8f2bb.firebasestorage.app',
    iosBundleId: 'com.example.proect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXvnvTR06b3HW89YmzLXVn_-7EsFXK5Vk',
    appId: '1:1084788300297:ios:c33fe4ca2299ea437b36d8',
    messagingSenderId: '1084788300297',
    projectId: 'school-proect-8f2bb',
    storageBucket: 'school-proect-8f2bb.firebasestorage.app',
    iosBundleId: 'com.example.proect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFqkw05jiFSe3DBHwL3bFJDXdHew3IWtw',
    appId: '1:1084788300297:web:f7d39c3dbc3e916e7b36d8',
    messagingSenderId: '1084788300297',
    projectId: 'school-proect-8f2bb',
    authDomain: 'school-proect-8f2bb.firebaseapp.com',
    storageBucket: 'school-proect-8f2bb.firebasestorage.app',
    measurementId: 'G-PS1PF961JR',
  );
}
